### ISSUE TITLE
Span is not created

### ISSUE THREAD

**Issue by billibit** [ttony/opentracing-java-annotation#2]
I created the following method to test the @Span but no span has been created, Any reason why?

public class SpanTest {
	
	@NewSpan(operationName="SpanTest.once")		
	public void processMessagesSayHelloOnce(int i) {
...
 	}
}

I used POM.
"
	  <dependency>
	    <groupId>io.github.ttony</groupId>
	    <artifactId>opentracing-java-annotation</artifactId>
	    <version>1.1.0</version>
	  </dependency>
"

**Comment by ttony** [comment]
hi...  are you using Spring or Non-Spring? if you are using non-spring, then you need to include VM Options as -javaagent:<PATH_TO_ASPECTJ>/aspectjweaver-1.9.4.jar... The library is heavily depend on AspectJ to do the weaving.

**Comment by ttony** [comment]
is this fix the problem?
